// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportAssets(arg1) {
  return window['go']['app']['App']['ExportAssets'](arg1);
}

export function StartQuery(arg1) {
  return window['go']['app']['App']['StartQuery'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function StopQuery() {
  return window['go']['app']['App']['StopQuery']();
}
