// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {types} from '../models';
import {context} from '../models';

export function ExportAssets(arg1:Array<string>):Promise<void>;

export function StartQuery(arg1:app.QuerySetting):Promise<Array<types.Asset>>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopQuery():Promise<void>;
