name: push

on:
  push:
    branches:
      - 'main'

jobs:
  test-windows-app:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Display node/npm version
        run: |
          node -v
          npm -v

      - uses: actions/checkout@v4
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Display go version and GOPATH
        run: |
          go version
          go env get GOPATH

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor

      - name: Build
        run: |
          wails build
