name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-windows-app:
    needs: release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Display node/npm version
        run: |
          node -v
          npm -v

      - uses: actions/checkout@v4
      - name: Setup Go 1.22.0
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.0'

      - name: Display go version and GOPATH
        run: |
          go version
          go env get GOPATH

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor

      - name: Build
        run: |
          wails build

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./build/bin/zfofa.exe
          asset_name: zfofa_win.exe
          asset_content_type: application/octet-stream
